apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-db
spec:
  replicas: 1
  serviceName: svc-mysql
  selector:
    matchLabels:
      app: wordpress-db
  template:
    metadata:
      name: wordpress-db
      labels:
        app: wordpress-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: db-password
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi